// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "awscognitodemowebapp-20200103204926-hostingbucket-local",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://awscognitodemowebapp-20200103204926-hostingbucket-local.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:172c1381-09d5-4464-8aae-cd57ceebb0f2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7eMekq1Uw",
    "aws_user_pools_web_client_id": "16mnmfng1llqu6ai9jrjdqp7a6",
    "oauth": {}
};


export default awsmobile;
